<H4><?php echo __('Lastest Comment For Post ID ') . $block->getPostID() ?></H4>


<?php
$comments = $block->getComments(); ?>
<?php if($comments->count()>0){ ?>
    <ul class="blog-post-list">
        <?php foreach ($comments as $cmt) { ?>
            <li class="blog-post-list-item"><?php echo $cmt->getAuthor() ?>
                <div class="blog-post-item-content"><?php echo $cmt->getContent() ?></div>
                <div class="blog-post-item-meta">
                    <small>Created at: <?php echo $cmt->getCreationTime() ?></small>
                </div>
            </li>
        <?php } ?>
    </ul>
<?php } else echo "No comment found!"; ?>
<script type="text/x-magento-init">
    {
        "*": {
            "OpenTechiz_Blog/js/commentajax": {
                "AjaxCommentPostUrl": "<?php echo $block->getFormAction() ?>",
                "AjaxCommentLoadUrl": "<?php echo $block->getAjaxUrl() ?>",
                "AjaxPostId": "<?php echo $block->getPostID(); ?>",
                "AjaxNotificationLoadUrl": "<?php echo $block->getAjaxNotificationLoadUrl(); ?>"
            }
        }
    }
</script>